### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by houtknots** [bergerhealer/TC-Coasters#11]
I have a problem with TC-Coasters, the map does not show anything and evertime I open the map the following error messages get displayed.

Traincarts, BKcommonlib and TC-Coasters are all update to the lastest version.

I Run Paper Spigot 1.14.4
https://media.houtknots.nl/photo/2019-10-29_23-26-00.png

```
[23:23:11] [Server thread/WARN]: [TCCoasters] Task #132 for TCCoasters v1.14.4-v1 generated an exception
java.lang.RuntimeException: Error while sending packet:
	at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler.sendPacket(ProtocolLibPacketHandler.java:158) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.PacketUtil.sendPacket(PacketUtil.java:75) ~[?:?]
	at com.bergerkiller.bukkit.common.map.MapSession$Owner.updateMap(MapSession.java:235) ~[?:?]
	at com.bergerkiller.bukkit.common.map.MapDisplay.update(MapDisplay.java:370) ~[?:?]
	at com.bergerkiller.bukkit.common.map.MapDisplay$1.run(MapDisplay.java:810) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler.sendPacket(ProtocolLibPacketHandler.java:154) ~[?:?]
	... 11 more
```

**Comment by weeryan17** [comment]
"lastest version" as in latest available on spigot?
Also do you have protocolib installed? If so you need to use the development version of protocolib http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by houtknots** [comment]
@weeryan17 Thank you, I just downloaded the latest version on the spigot plugin page not the development build. 

It works again thank you very much 👍
